# Generated by Django 3.0.14 on 2021-08-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Folder')),
            ],
        ),
    ]
