# Generated by Django 3.0.14 on 2021-08-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0001_add_file_and_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('title', 'folder', 'owner'), name='file_title_folder_owner_key'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(folder=None), fields=('title', 'owner'),
                                               name='file_title_owner_key'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('title', 'parent', 'owner'),
                                               name='folder_title_parent_owner_key'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(folder=None), fields=('title', 'owner'),
                                               name='folder_title_owner_key'),
        ),
    ]
