# Generated by Django 3.0.14 on 2021-08-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_add_file_and_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='folder_id',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
