# Generated by Django 3.0.14 on 2021-08-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20210819_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='folder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Folder'),
        ),
    ]
