# Generated by Django 3.0.14 on 2021-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_add_owner_field_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
