# Generated by Django 3.0.14 on 2021-09-23 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_add_relative_key_to_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
