# Generated by Django 3.0.14 on 2021-10-04 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0005_add_uuid_field_folder_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SharedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.File')),
                ('permissions', models.ManyToManyField(to='assets.Permissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='shared',
            field=models.ManyToManyField(through='assets.SharedTable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sharedtable',
            constraint=models.UniqueConstraint(fields=('file', 'user'), name='shared_file_user_key'),
        ),
    ]
