# Generated by Django 3.0.14 on 2021-10-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_add_shared_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnail_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
