# Generated by Django 3.0.14 on 2021-10-07 14:28
import os

from django.db import migrations


def get_extensions(apps, schema_editor):
    model = apps.get_model('assets', 'File')
    for row in model.objects.all():
        row.extension = os.path.splitext(row.title)[1]
        row.save(update_fields=['extension'])


def reverse_extensions(apps, schema_editor):
    model = apps.get_model('assets', 'File')
    for row in model.objects.all():
        row.extension = ''
        row.save(update_fields=['extension'])


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0007_add_file_fields'),
    ]

    operations = [
        migrations.RunPython(get_extensions, reverse_code=reverse_extensions)
    ]
