# Generated by Django 3.0.14 on 2021-10-11 21:45

import os

from django.contrib.auth import get_user_model
from django.db import migrations


def create_superuser(apps, schema_editor):
    user_model = get_user_model()
    if not user_model.objects.filter(username=os.getenv('ADMIN_USERNAME')).exists():
        user_model.objects.create_superuser(username=os.getenv('ADMIN_USERNAME'),
                                            password=os.getenv('ADMIN_PASSWORD'),
                                            email=os.getenv('ADMIN_EMAIL'))


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0009_delete_null_in_extention'),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_code=migrations.RunPython.noop),
    ]
