# Generated by Django 3.0.14 on 2021-10-11 21:45

from django.db import migrations


def create_permissions(apps, schema_editor):
    Permissions = apps.get_model('assets', 'Permissions')
    Permissions.objects.all().delete()
    permission = [
        Permissions(title='Download', name='read_only'),
        Permissions(title='Rename', name='rename_only'),
        Permissions(title='Delete', name='delete_only')
    ]
    Permissions.objects.bulk_create(permission)


def reverse_permissions(apps, schema_editor):
    Permissions = apps.get_model('assets', 'Permissions')
    Permissions.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0009_delete_null_in_extention'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_code=reverse_permissions),
    ]
