# Generated by Django 3.0.14 on 2021-11-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_initial_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='extension',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
